[package]
name = "yuumu_moe"
version = "0.1.0"
authors = ["YuumuKonpaku <MLTT2HoTT@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.56"
# yew = "0.10.0"
yew = { git = "https://github.com/yewstack/yew" }
